### ISSUE TITLE
Add Native Introspection

### ISSUE THREAD

**Issue by monsterbitar** [stevenroose/covenants.info#18]
I think you should consider established opcodes in other bitcoin derived chains as possible ways forward for UTXO based covenants.

The benefits are:

1) You already got a testnet
2) Opcodes demonstrated secure in the wild
3) Free documentation
4) Better compatibility with existing chains
5) Existing testing frameworks

Here's a link to technical specification, same document has abstracts, motivation etc:

https://documentation.cash/protocol/forks/chips/2022-05-native-introspection-opcodes.html#technical-specification

**Comment by stevenroose** [comment]
This is already present: https://covenants.info/proposals/direct-introspection/
